### ISSUE TITLE
not defined

### ISSUE THREAD

**Issue by ZenoMilk12** [TheGloriousDuck/MCPSnippets#1]
what's up with the gl stuff, i know GlStateManager but glDisable or glSomething it does not work

**Comment by TheGloriousDuck** [comment]
Instead of using GlStateManager, do this:
`import static org.lwjgl.opengl.GL11.*`
This imports all static methods and fields inside the GL11 class.
GlStateManager is generally recommended to use but meh

**Comment by ZenoMilk12** [comment]
ok thank you so much!
